### PR TITLE
minor adjestments

### PR DESCRIPTION
**Pull request by ctf0**
made a new folder for msgs and made some formatting to the readme.

### CODE REVIEW

**Comment by dericofilho** [comment]
I appreciate this PR. I will pull this into a branch and merge manually. I will specifically avoid bikeshedding.

**Comment by ctf0** [comment]
i dont know what `bikeshedding` means but this PR was just a simple way of saying thanx for all ur hard work.

**Comment by dericofilho** [comment]
@ctf0 Thanks :)

**Comment by dericofilho** [comment]
Thank you, @ctf0 

Merged.

**Comment by ctf0** [comment]
np ,ur welcome :metal:

**Pull request merged**
